# Generated by Django 5.0 on 2023-12-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(default='anonymous.jpg', upload_to='images/'),
        ),
    ]
